### ISSUE TITLE
Step by step guide

### ISSUE THREAD

**Issue by saeeds255** [evilive3000/poloniex-orderbook#3]
Hi,
Can you tell me step by step what should I do ?
where to put the example code and how to run it on ubuntu ?
I type "npm install poloniex-orderbook" but it returns following errors

```
> bufferutil@1.2.1 install /root/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/w                                                                                        hich/which.js:14:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:6                                                                                        9:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:8                                                                                        1:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:1                                                                                        6
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/                                                                                        isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/                                                                                        isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-                                                                                        gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/bufferutil
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "poloniex-orderbook"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/poloOrderbook/npm-debug.log
```

**Comment by evilive3000** [comment]
Hi, what's node version do you have?

**Comment by saeeds255** [comment]
node version is 6.3.1

**Comment by evilive3000** [comment]
@saeeds255 you did everything right, but you need some system tools to install. According to the [answer](http://stackoverflow.com/a/14772631/965106) on stackoverflow with same issue you have to run command `$ sudo apt-get install build-essential`. 
Let me know if it helps you. GL.

**Comment by saeeds255** [comment]
Thanks !
I did that and I got the following errors 

```
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "poloniex-orderbook"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ENOSELF

npm ERR! Refusing to install poloniex-orderbook as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/poloOrderbook/poloniex-orderbook/npm-debug.log
```

BUT I made a file named poloniex-orderbook.js then typed node poloniex-orderbook and it worked !

**Comment by evilive3000** [comment]
ok, let's try do it step by step:
- create folder for your project `mkdir polo` and go to this folder `cd polo`
- interactively create a package.json file `npm init`
- install the module `npm install poloniex-orderbook --save`. Flag `save` will add this module to package.json dependencies section.
- create file `touch index.js`
- open `index.js` file with your favorite editor and paste the code: 

``` javascript

"use strict";

const PoloBook = require('poloniex-orderbook');

const polobook = (new PoloBook('btc_eth')).start();

(function run() {
  console.log(`---===${new Date().toLocaleTimeString()}===---`);

  for(const type of ['asks', 'bids']) {
    console.log(`::::::${type}::::::`);
    for(const [rate, amount] of polobook[type].slice(0, 10)) {
      console.log(`${rate}: ${amount}`);
    }
  }

  setTimeout(run, 1000);
})();
```
- and the very last step is to run the app `node index.js`. You'll get the list of asks and bids with update rate 1Hz.
